# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Display": "00_cli.ipynb",
         "main": "00_cli.ipynb",
         "CLI": "00_cli.ipynb",
         "Duo": "00_cli.ipynb",
         "writeOut": "00_cli.ipynb",
         "nrPepDB": "00_cli.ipynb",
         "pepDB2Fa": "00_cli.ipynb",
         "subPepDB": "00_cli.ipynb",
         "intersectInQuery": "00_cli.ipynb",
         "run_blast": "01_blast.ipynb",
         "load_blast": "01_blast.ipynb",
         "run_mafft": "02_msa.ipynb",
         "writeAln": "02_msa.ipynb",
         "fa2sto": "02_msa.ipynb",
         "alnFile2hmmFile": "03_hmmer.ipynb",
         "load_hmm": "03_hmmer.ipynb",
         "run_hmmsearch": "03_hmmer.ipynb"}

modules = ["cli.py",
           "blast.py",
           "msa.py",
           "hmmer.py"]

doc_url = "https://tijeco.github.io/duomolog/"

git_url = "https://github.com/tijeco/duomolog/tree/{branch}/"

def custom_doc_links(name): return None
