# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/03_hmmer.ipynb (unless otherwise specified).

__all__ = ['alnFile2hmmFile', 'load_hmm', 'run_hmmsearch']

# Cell
import pyhmmer
import shlex, subprocess
import os

# Cell
def alnFile2hmmFile(alnFile):
	devnull = open(os.devnull, 'w')
	hmmFile = alnFile+".hmm"
	call_list = ''.join(['hmmbuild ',hmmFile,' ', alnFile])
	commands = shlex.split(call_list)
	subprocess.Popen(commands, stdin=subprocess.PIPE, stderr=subprocess.PIPE,stdout=devnull).communicate()
	
	return hmmFile

# Cell
def load_hmm(hmmFile):
    with pyhmmer.plan7.HMMFile(hmmFile) as h:
        hmm = next(h)
    return hmm

# Cell
def run_hmmsearch(queryFile, alnFile=None, hmmFile=None, writeHMM=True):
    if writeHMM:
        if alnFile != None:
            hmmFile = alnFile2hmmFile(alnFile)
        hmm = load_hmm(hmmFile)
    else:
        hmm = build_hmm(alnFile)

    with pyhmmer.easel.SequenceFile(queryFile) as seq_file:
        sequences = [ seq.digitize(hmm.alphabet) for seq in seq_file ]
    pipeline = pyhmmer.plan7.Pipeline(hmm.alphabet)
    hits = pipeline.search_hmm(hmm, sequences) # Has lots of goodies!
    return hits
